Fixed Provider ID format
openshift/machine-api-provider-powervs pull request #16
Opened 2022-04-07 13:11 UTC by Karthik-K-N

This PR contains following changes
1. To fix the ProviderID format when ServiceInstance.ID or ServiceInstance.Name is passed in spec 
2. Storing the ServiceInstanceID in machine status so that it can be easily fetched against making a query to Power Cloud
3. Storing the ServiceInstanceID in status field so that user will not edit

Fixes: [15](https://github.com/openshift/machine-api-provider-powervs/issues/15)

2022-04-07 14:00 UTC, Karthik-K-N commented
/hold
Not able to test the changes, Facing some weired power cloud api issues

```
controller/machine_controller "msg"="Reconciler error" "error"="failed to get the instance list, Error: failed to Get all PVM Instances of Power Instance e449d86e-c3a0-4c07-959e-8557fdf55482 :[GET /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances][500] pcloudPvminstancesGetallInternalServerError  &{Code:0 Description:an error has occurred; please try again: unable to get new compute instance client for 15ea5428420d4d47be42e19332645a18: unable to get new compute instance: unable to get provider client: unable to authenticate powervc client after 5 retries for project-id 15ea5428420d4d47be42e19332645a18; most recent error: Post \"https://192.168.24.137:5000/v3/auth/tokens\": OpenStack connection error, retries exhausted. Aborting. Last error was: dial tcp 192.168.24.137:5000: connect: connection refused Error:internal server error Message:}" "name"="rdr-ipi-kkn-c8vmm-master-0" "namespace"="openshift-machine-api" 
```

2022-04-13 12:37 UTC, Karthik-K-N commented
/hold cancel
Tested and works as expected, @mkumatag Please take a look.

2022-04-14 06:11 UTC, mkumatag requested changes

2022-04-14 06:11 UTC, mkumatag commented on pkg/actuators/machine/machine_scope.go
> +		klog.Infof("Found ServiceInstanceID from providerStatus %s", *serviceInstanceID)
wondering if this condition can be checked first and remaining later.

2022-04-14 06:11 UTC, mkumatag commented on pkg/actuators/machine/reconciler.go
> +		klog.Infof("Found ServiceInstanceID from providerStatus %s", serviceInstanceID)
if we are assigning this one then can we just stick to this alone for deriving the provider id?

2022-04-20 04:50 UTC, mkumatag approved these changes
/lgtm
/approve

2022-04-20 04:52 UTC, merged