MULTIARCH-3668: Update make file to use latest golang
openshift/machine-api-provider-powervs pull request #47
Opened 2023-06-07 07:00 UTC by Karthik-K-N

Updated golang version used for running tests
Updated podman command to remove :Z as its not supported

2023-06-07 08:03 UTC, mkumatag requested changes

2023-06-07 08:18 UTC, Karthik-K-N commented on Makefile
> -BUILD_IMAGE ?= registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.19-openshift-4.12
Yes sure, shall we use this then
```
registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.20-openshift-4.14
```

2023-06-07 09:42 UTC, mkumatag commented on Makefile
> -BUILD_IMAGE ?= registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.19-openshift-4.12
yes, lets use that.

2023-06-07 09:55 UTC, mkumatag approved these changes
/lgtm

again please create a jira item and assign

2023-06-14 15:51 UTC, deepsm007 commented
/label jira/valid-bug

2023-06-14 16:08 UTC, merged